FROM node:22-bookworm AS node

FROM golang:1.26-bookworm

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=1000
ARG AIR_VERSION=v1.67.4

COPY --from=node /usr/local/ /usr/local/

RUN apt-get update \
    && apt-get install -y --no-install-recommends git postgresql-client sudo \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd --gid "$USER_GID" "$USERNAME" \
    && useradd --uid "$USER_UID" --gid "$USER_GID" --create-home --shell /bin/bash "$USERNAME" \
    && echo "$USERNAME ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/$USERNAME" \
    && chmod 0440 "/etc/sudoers.d/$USERNAME" \
    && GOBIN=/usr/local/bin go install "github.com/air-verse/air@$AIR_VERSION" \
    && npm install -g "@opencode/cli" \
    && mkdir -p /go/pkg/mod /home/$USERNAME/.cache/go-build /home/$USERNAME/.npm /workspace \
    && chown -R "$USER_UID:$USER_GID" /go /home/$USERNAME /workspace

ENV GOPATH=/go
ENV PATH=/go/bin:${PATH}

WORKDIR /workspace
USER dev

CMD ["sleep", "infinity"]
